name: Coding Styles

on:
  pull_request:

jobs:
  codingStyle:
    name: "Coding Style"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Configure PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2

      - name: "Install dependencies"
        run: composer install --prefer-dist --no-progress

      - name: "PHPCsFixer"
        run: composer csFixer

      #- name: Rector
      #  run: composer rector

      - name: "PHPStan Analyse"
        run: composer phpstan
